# Site settings
title: My portfolio
email: ck0825@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my portfolio showcase
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://rueni.github.io" # the base hostname & protocol for your site
twitter_username: ckim79
github_username:  rueni

# Build settings
markdown: kramdown
